name: Build DEB + Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Prepare package
        run: |
          rm -rf package
          mkdir -p package/DEBIAN
          mkdir -p package/opt/html-app

          find . -maxdepth 1 \
            ! -name "." \
            ! -name "package" \
            ! -name ".github" \
            -exec cp -r {} package/opt/html-app/ \;

      - name: Build DEB
        run: |
          VERSION=1.0.${GITHUB_RUN_NUMBER}

          cat <<EOF > package/DEBIAN/control
Package: html-app
Version: $VERSION
Section: web
Priority: optional
Architecture: all
Maintainer: Davi
Description: HTML app convertido para pacote .deb
EOF

          dpkg-deb --build package html-app-$VERSION.deb

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          files: |
            html-app-1.0.${{ github.run_number }}.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
